### PR TITLE
Fix for #126 as initially proposed by @bbrangeo; pushing for speed (since i need it.. :) )

### LINKED ISSUE #126: cannot import name 'remove_expired_responses' from 'requests_cache'
python version: 3.10.12
pygbif version: 
```
Name: pygbif
Version: 0.6.3
Summary: Python client for GBIF
Home-page: http://github.com/gbif/pygbif
Author: Scott Chamberlain
Author-email: myrmecocystus@gmail.com
License: MIT
Location: /usr/local/lib/python3.10/dist-packages
Requires: appdirs, geojson-rewind, geomet, matplotlib, requests, requests-cache
Required-by:
```

Getting the following error upon import:
```
    import pygbif
  File "/usr/local/lib/python3.10/dist-packages/pygbif/__init__.py", line 44, in <module>
    from .caching import caching
  File "/usr/local/lib/python3.10/dist-packages/pygbif/caching.py", line 6, in <module>
    from requests_cache import remove_expired_responses
ImportError: cannot import name 'remove_expired_responses' from 'requests_cache' (/usr/local/lib/python3.10/dist-packages/requests_cache/__init__.py)
```

### PR DESCRIPTION
**Pull request by lucbettaieb**
## Description
Fixes #126 with changes proposed by @bbrangeo

## Related Issue
Fixes #126

### CODE REVIEW

**Comment by lucbettaieb** [comment]
Tested locally:
```
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygbif
>>>
```

**Comment by lucbettaieb** [comment]
Thanks @CecSve !

**Comment by airnst** [comment]
Sorry to ask here, but does anyone happen to know when the update will be released to make new installations work?

**Comment by lucbettaieb** [comment]
@airnst Not sure, but if you are blocked you can install from source with pip:
```
pip install git+https://github.com/gbif/pygbif.git@master
```

i think that should work...

**Comment by abubelinha** [comment]
I am not sure but I think this fix raised a new problem see #145 
The specific error line was one introduced in this fix.
If I downgrade to pygbif==0.6.3 it fixes #145

**Pull request merged**
